### ISSUE TITLE
working with d3-request types 

### ISSUE THREAD

**Issue by vishnu038** [tomwanzek/d3-ng2-service#102]
the bundle does  not include the d3-request types so that i am not able to access d3.csv  how can i add this 
angular 

import {csv} from 'd3-request';

its not working help.

I  Installed  d3-request.

**Comment by tomwanzek** [comment]
As this service is intended for use with Angular,  d3-request is not
included by design. As an implied best practice, http communication should
use Angular’s features.

Thanks for understanding.
