### ISSUE TITLE
build failing while running the project

### ISSUE THREAD

**Issue by kodiraj** [tomwanzek/d3-ng2-service#23]
94% asset optimizationError in bail mode: [default] /Users/kodiraj/Documents/workspace/future/src/main/webapp/ui/nextgenportal/node_modules/@types/geojson/index.d.ts:21:16 
Duplicate identifier 'Position'.

**Comment by tomwanzek** [comment]
Can you please provide more context regarding your project setup? GeoJSon types are used as a dependency in the TS definitions for d3-geo, which in turn are a dependency of this service.

**Comment by tomwanzek** [comment]
Also, the GeoJSon types wrap `Position` in a `GeoJSON` namespace, so it does not seem self-evident to me, how a duplicate identifier on `Position` would naturally arise in your project.

**Comment by tomwanzek** [comment]
Closing as required information not provided to date.
