### ISSUE TITLE
d3v4-ng2-demo link is not working

### ISSUE THREAD

**Issue by rajendra2** [tomwanzek/d3-ng2-service#3]
example project (https://github.com/tomwanzek/d3v4-ng2-demo) is redirecting to 404 page on github.

**Comment by tomwanzek** [comment]
Yep, apologies for that, I was ready to publish from my local repo, but then decided that I to look into the latest angular-cli webpack.beta.8 beforehand. Should be up shortly. I am trying to minimize the headache, if too much changes on that side for a simple demo...
