### ISSUE TITLE
How to draw a d3 stack barchart using ng-2service?

### ISSUE THREAD

**Issue by erajabi** [tomwanzek/d3-ng2-service#41]
I am trying to draw a stack bar chart (like this code https://bl.ocks.org/DimsumPanda/689368252f55179e12185e13c5ed1fee
) using d3-ng2 service, in a Angularjs2 component. The following line works in Javascript:

var datasample="ethnicity,F Under 25,F Over 75,F 25 to 50,F 50 to 75,M Under 25,M Over 75,M 25 to 50,M 50 to 75\n"+
          "Asian,327,296,332,309,306,330,307,323\n"+
          "Black,294,302,330,305,295,363,322,292";
          var data= this.d3.csvParse(datasample);
          g.selectAll(".serie")
            .data(d3.stack().keys(data.columns.slice(1))(data)

However, I get the following error, when I use it in typescript inside the component.

Argument of type 'DSVParsedArray<DSVRowString>' is not assignable to parameter of type '{ [key: string]: number; }[]'.
  Types of property 'includes' are incompatible.
    Type '(searchElement: DSVRowString, fromIndex?: number) => boolean' is not assignable to type '(searchElement: { [key: string]: number; }, fromIndex?: number) => boolean'.
      Types of parameters 'searchElement' and 'searchElement' are incompatible.
        Type '{ [key: string]: number; }' is not assignable to type 'DSVRowString'.
          Index signatures are incompatible.
            Type 'number' is not assignable to type 'string'.

I import d3-ngservice to use d3 object.

import { D3Service, D3, Selection } from 'd3-ng2-service';
It seems I should rewrite d3.stack().keys line in a typescript format. I tried to import 'Stack' class from ng2service as well, but it did not work.

**Comment by tomwanzek** [comment]
This does not appear to be an issue with the `d3-ng2-service`.

The [TS definitions governing `csvParse(...)`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-dsv/index.d.ts#L29) have two signatures, one of which allows for a generic to control the data structure of a parsed line.

Similarly the [TS definitions for `d3.stack()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-shape/index.d.ts#L2224) have several signatures supporting generics to control the `Datum` type and `Key` type.

Without using the generics the defaults are assigned, which in your case seems to create the type mismatch.

So please, review/define the data types for the generics when you are parsing and then passing into stack and ensure their alignment.

You can have a peak at the definition test files [d3-dsv](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-dsv/d3-dsv-tests.ts) and [d3-shape](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-shape/d3-shape-tests.ts) for some examples of how the generics are used. Note that the examples are a bit artificial, as they are only shape tests, but they are still a good reference point.

As this is not an issue related to this service, I am going to close it here. If the above info did not help to get you on the way to resolving your question, please:
* Use stackoverflow for the question,
* Open an issue on DefinitelyTyped, if you find that any of the above definitions are too strict/erroneous and need rewriting.

Thanks for understanding. T 😄
