### ISSUE TITLE
how would I update a component variable in callback?

### ISSUE THREAD

**Issue by grimace** [tomwanzek/d3-ng2-service#46]
I'm trying to update an ng2 component variable from my mouseOver callback, but I can't seem to update any member variables in my component
`
  var enter = svg.enter()
    .append("circle")
    .attr("r", 10)
    .on("mouseover", _mouseOver)
    .on("mouseout",_mouseOut)
`

**Comment by tomwanzek** [comment]
Please use this issues log for (suspected) bugs and feature requests related to this service only. For general "how to" questions, please use StackOverflow. Thanks for understanding. 😄 

By the same token, please see the following related [SO answer](http://stackoverflow.com/questions/38945311/typescript-d3-v4-context-of-this-in-d3-drag-onend-this-dragended/40314241#40314241), I provided to a similar question.
