### ISSUE TITLE
selection-multi not available

### ISSUE THREAD

**Issue by fi4sk0** [tomwanzek/d3-ng2-service#48]
Hey there,

I'm having trouble using the "styles" and "attrs" method on Selections. I looked through the source and it seems the `d3-selection-multi` package gets exported in the `src/bundle-d3.d.ts` file but not in `src/bundle-d3.js`. When I manually add a line that exports everything from d3-selection-multi, I can use "styles" and "attrs".

bundle-d3.js (excerpt):

    export * from 'd3-scale';
    export * from 'd3-selection';
    export * from 'd3-shape';

bundle-d3.d.ts (excerpt):

    export * from 'd3-scale';
    export * from 'd3-selection';
    export * from 'd3-selection-multi';
    export * from 'd3-shape';

Thanks for you time and for your awesome work!

**Comment by tomwanzek** [comment]
@fi4sk0 Thanks for catching this issue and pinning it down right away. Unlike `d3-transition`, `d3-selection-multi` is purely side-effect in JavaScript. So as compilation drops the exported interfaces/types there is no remaining export dependency.

I am testing out a minor tweak locally.

**Comment by tomwanzek** [comment]
@fi4sk0 Thx again. The fix is in the patch release 1.10.1.

**Comment by fi4sk0** [comment]
@tomwanzek thanks! You're awesome!
