### ISSUE TITLE
Getting d3.event

### ISSUE THREAD

**Issue by ocombe** [tomwanzek/d3-ng2-service#5]
I'm not using this lib, but I use a similar enough code that you will get the same problem: when importing * from d3-selection, then it will export a constant d3.event value.
This value is never updated by new events.

I'm not sure if this is a problem with es6 imports or just webpack...

The trick that I use for angular 2, adding a getter for event on the service that uses require to get a "fresh" event everytime I need it:

```ts
get event() {
  return require("d3-selection").event;
}
```

Then in your code call `d3Service.event` to get the event, instead of `d3.event`

**Comment by tomwanzek** [comment]
Thanks for the take. I do not seem to experience the problem so far. The associated demo I built in [tomwanzek/d3-ng2-demo](https://github.com/tomwanzek/d3-ng2-demo) and the [live github page](https://tomwanzek.github.io/d3-ng2-demo/) for a few reference components seems to handle the events as expected.

The injected service singleton seems to work alright in the project generated from the angular-cli webpack version (1.0.0-beta.11-webpack.8. with some dependency fixes for typescript and awesome-typescript-loader.)

Did you experience a different event-handling use case, where you saw the live-binding issue?

**Comment by ocombe** [comment]
Hmm I need to recheck, maybe it was fixed in one of the patches

**Comment by ocombe** [comment]
No I still have the problem but I import directly from `d3-selection` in a vendor.ts files that is bundled for all my modules, maybe that's the problem, I don't create a new instance of the d3 lib for each component

**Comment by tomwanzek** [comment]
Try writing it as a service, that way you have a singleton, which is created once and that is the one you pull in. Feel free to look at the source code in the repo, I always just pull directly from the import that feeding the service.

Another possible explanation could have to do with which module system the TS code is compiled to. I matched mine essentially to the one used by angular-cli. But, if once goes `commonjs`, say, that might lead to a different experience with `d3.event`.

**Comment by tomwanzek** [comment]
I'm closing this issue. If you experience the issue using this service, let me know and I will reopen it. Cheers.

**Comment by ocombe** [comment]
Yup, no prob :)
