### ISSUE TITLE
d3.tsv not working

### ISSUE THREAD

**Issue by Alan-mag** [tomwanzek/d3-ng2-service#50]
I'm having trouble using d3.tsv after import the D3Service and was wondering if anyone else was experiencing similar problems? I was able to get Mike Bostock's tutorial working up until using the d3.tsv function for loading in external data from a file. (https://bost.ocks.org/mike/bar/2/) 

 Am I missing a module import? (I've included D3Service, D3, and Selection in my chart component.

**Comment by tomwanzek** [comment]
`tsv(...)` is part of the **d3-request** module, which is not part of `d3-ng2-service` (see [here](https://github.com/tomwanzek/d3-ng2-service#scope-of-d3-functionality). As this service is geared towards use with Angular, please use the Angular `http`-service for obtaining data from the server. 

Nevertheless, the `d3-ng2-service` provides the data _parsing_ capabilities contained in the **d3-dsv** module. I.p. you _can_ use `tsvParse(...)` to parse the data you loaded with Angular's `http` service.

So there is some rework required to convert the referenced example. Should you have further questions as to how to accomplish this, please use StackOverflow. Hope this clarifies. Cheers, T

**Comment by Alan-mag** [comment]
Thanks Tom, I appreciate it.

**Comment by tomwanzek** [comment]
I updated the README to add clarity.
