### ISSUE TITLE
not accessible methods

### ISSUE THREAD

**Issue by kaktus42** [tomwanzek/d3-ng2-service#51]
I imported the library as told in the Readme. However, I can't access e.g. `this.d3.csv(filename, ...)` or `this.d3.request(filename)`.
The error I am getting is:
> TS2339: Property 'csv' does not exist on type 'typeof "[path]/d3-ng2-servi...'.

My import in the component file is: `import { D3Service, D3, Selection } from 'd3-ng2-service';` am I missing imports to be able to use this?
Calling `this.d3.range(300);` works.

I found #13 but it didn't help me.

**Comment by tomwanzek** [comment]
As commented on in issue #50 and indicated in the API documentation [here](https://github.com/tomwanzek/d3-ng2-service#scope-of-d3-functionality), **d3-request** is not part of the D3 Angular 2+ service. Please use Angular functionality like the `http` service for client/server communication.

You are however able to use the data parsing methods through this services, as it provides the **d3-dsv** functionality.

I will add a further clarifying comment to the README to specifically call out the `http` service.

**Comment by tomwanzek** [comment]
I updated the README to add clarity.
