### ISSUE TITLE
Missing CurveFactory Type

### ISSUE THREAD

**Issue by Justus-Maier** [tomwanzek/d3-ng2-service#65]
I would like to select curve interpolation by attribute `<svg:path my-curve-directive interpolate="sabertooth" ..>`.. 
```typescript
import {
  D3,
  D3Service,
  Line,
  ScaleLinear,
  ScaleTime,
  Selection,
  Path,
  CurveFactory // <- missing
} from 'd3-ng2-service';


interface IRealtimeGraphData {
  time: number;
  value: number;
}

interface IInterpolationMap {
  [name: string]:  Function // should be: CurveFactory,
}

@Directive({
  selector: 'my-curve-directive'
})
export class ComposableCurveDirective implements OnInit {
  private d3: D3;
  private parentNativeElement: any;
  // private d3Svg: Selection<SVGSVGElement, any, null, undefined>;
  private d3G: Selection<SVGGElement, any, null, undefined>;

  protected line: Line<IRealtimeGraphData>;
  protected path: Path | Selection<SVGGElement, any, null, undefined>; // another problem here..

  // [..]

  @Input() interpolate = 'sabertooth';
  protected interpolations: IInterpolationMap = {};

  constructor( element: ElementRef, d3Service: D3Service ) {
    this.d3 = d3Service.getD3();
    this.parentNativeElement = element.nativeElement;
    this.interpolations['sabertooth'] = this.d3.curveStepBefore;
    // TODO add more interpolations
  }

//...
}
```
How can I access the CurveFactory Type? It's there but I can't import it..

`TS2345: Argument of type 'Function' is not assignable to parameter of type 'CurveFactory | CurveFactoryLineOnly'.
  Type 'Function' is not assignable to type 'CurveFactoryLineOnly'.
    Type 'Function' provides no match for the signature '(context: Path | CanvasRenderingContext2D): CurveGeneratorLineOnly'`

**Comment by tomwanzek** [comment]
Thanks for reporting this issue, clearly an omission. I just did a full scan across all interface and type re-exports and will publish a patch release.

**Comment by tomwanzek** [comment]
@Justus-Maier Release has been published, including to npm.
