### ISSUE TITLE
[d3-scale] Can't pass string range to linear scale

### ISSUE THREAD

**Issue by rybaczewa** [tomwanzek/d3-ng2-service#72]
Passing string range to `scaleLinear` like so:
```
import * as d3Scale from 'd3-scale';

d3Scale.scaleLinear()
  .domain([1, 20])
  .clamp(true)
  .range(['#fff', '#000']);
```

`Argument of type 'string[]' is not assignable to parameter of type 'number[]'.`

As seen [here](https://github.com/d3/d3-scale#continuous_range), this should be possible:

> Unlike the domain, elements in the given array need not be numbers; any value that is supported by the underlying interpolator will work

**Comment by tomwanzek** [comment]
`scaleLinear()` as a scale factory and the corresponding interface `ScaleLinear` are parameterized with two generics (`Range` and `Output`). By default, i.e. `scaleLinear()`, these default to `number`.

To set another type for the range (and or scale output), please use `scaleLinear<string>()` or similar. The [JSDoc comments](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale/index.d.ts#L228) for the linear scale generator explain the usage for each of the signatures.

The service works as intended. 😄

**Comment by rybaczewa** [comment]
My bad then, I misunderstood how the function comments. Thanks for help.

**Comment by tomwanzek** [comment]
No worries.
