### ISSUE TITLE
'this' element

### ISSUE THREAD

**Issue by maiasmith** [tomwanzek/d3-ng2-service#78]
Hi,
I would like to be able to access the a d3 element's 'this' within an 'each()' function. 

`d3.selectAll(".txt").each(() => { d3.select(this) })`

However, the 'this' element that I receive is the component's 'this' element. I see in one of your demos that you have used an external function, such as:

`function helper(this: SVGTextElement) {
     d3.select(this);
    }`

However, I'm wondering if there is a way to operate on 'this' within the 'each' function.

**Comment by tomwanzek** [comment]
@maiasmith Please use StackOverflow for how-to questions. For one, the community to answer questions should be larger, and for another, it is easier for others in the same position to find answered questions.

In short, however:

(1) If you want to access the selected element in a D3 callback, you **must** use a proper function as the callback. Arrow functions are not permissible to achieve the context binding D3 performs under the hood.
(2) Make sure,  you use the TypeScript generic parameters supported on many methods of the D3 TypeScript  definitions, e.g.  `selectAll<...>(...)` to  control the type of the selected element(s).

For more info on the generics and the `this` context have a look at the JSDoc comments for the overloads in the TypeScript definitions e.g. for **d3-selection** in your case.

You can also have a look at my response to a somewhat related  question for **d3-drag** on SO. See [here](https://stackoverflow.com/questions/39413294/d3-drag-in-angular2/43573772#43573772)
