### ISSUE TITLE
a ERROR  occur in export * from 'd3-geo'

### ISSUE THREAD

**Issue by Huang9495** [tomwanzek/d3-ng2-service#79]
I download and install the library follow the command ' npm install d3-ng2-service --save ' from the Github (https://github.com/tomwanzek/d3-ng2-service) and configure the environment from the Github. The library of d3-geo is installed successfully.
The ERROR occurs after I initiate the angular-cli through 'ng server'

**## Environment**:Ubuntu14.04; framework:angular2;

**## The ERROR is showed here:**
ERROR in /home/kris-allen/angular-cli/PROJECT-test/src/app/maps/maps.component.ts (131,35): Property 'geo' does not exist on type 'typeof "/home/kris-allen/angular-cli/PROJECT-test/node_modules/d3-ng2-service/src/bundle-d3"'.

**## The code of the ERROR is promoted is here:**
          var transform = self.d3.geo.transform({point: self.projectPoint});
          self._path = self.d3.geo.path().projection(transform);

**# Where the wrong is??**

**Comment by tomwanzek** [comment]
@Huang9495 As the service is built on the basis of D3 version 4, there is no `geo` property. Please look at the [d3-geo](https://github.com/d3/d3-geo) API for the new D3 API. If needed consult the [official migration guide](https://github.com/d3/d3/blob/master/CHANGES.md) for D3 version 3 to 4.

In conclusion, the service in this repo should work just fine once you use the current API on your local `self.d3` variable.
